[package]
name = "dmc"
version = "0.1.0"
authors = ["alexdevteam <alexpro820@gmail.com>"]
edition = "2018"

[dependencies]
cgmath = "^0.18"
bitflags = "^1.2"
dashmap = "^4.0"
rayon = "^1.5"
ahash = "^0.7"

[lib]
name = "dmc"
path = "src/lib.rs"